In [57]:
import torch
import torch.nn as nn

In [58]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [59]:
data=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [60]:
data.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [61]:
data=data.drop(columns=['id','Unnamed: 32'])

In [62]:
data.shape

(569, 31)

In [63]:
xtrain,xtest,ytrain,ytest=train_test_split(data.iloc[:,1:],data.iloc[:,:1])

In [64]:
scaler=StandardScaler()
encoder=LabelEncoder()

In [65]:
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)
ytrain=encoder.fit_transform(ytrain)
ytest=encoder.transform(ytest)


c:\Users\AMAN KUMAR SINGH\.conda\envs\myenv310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\AMAN KUMAR SINGH\.conda\envs\myenv310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [66]:
xtrain

array([[-1.19795435,  0.15508805, -1.19739396, ..., -1.3842366 ,
        -1.58794009,  0.31848652],
       [-0.21463214,  0.54157255, -0.25785764, ..., -0.88513447,
        -0.42928655, -0.99429629],
       [-1.04876257, -0.69612627, -1.06741055, ..., -1.3842366 ,
        -0.3567677 , -0.57679755],
       ...,
       [-1.43223864, -0.83601943, -1.33428273, ..., -1.15807371,
        -2.05272002, -0.39481092],
       [ 0.82383225,  0.23096231,  0.73570304, ..., -0.05983291,
         0.62223685, -1.10078382],
       [-0.38817605,  1.07980556, -0.36143816, ...,  0.89730695,
         0.80023768,  1.06333582]], shape=(426, 30))

In [67]:
xtrain=torch.from_numpy(xtrain.astype(np.float32))

xtest=torch.from_numpy(xtest.astype(np.float32))
ytrain=torch.from_numpy(ytrain.astype(np.float32))
yest=torch.from_numpy(ytest.astype(np.float32))

In [68]:
xtrain

tensor([[-1.1980,  0.1551, -1.1974,  ..., -1.3842, -1.5879,  0.3185],
        [-0.2146,  0.5416, -0.2579,  ..., -0.8851, -0.4293, -0.9943],
        [-1.0488, -0.6961, -1.0674,  ..., -1.3842, -0.3568, -0.5768],
        ...,
        [-1.4322, -0.8360, -1.3343,  ..., -1.1581, -2.0527, -0.3948],
        [ 0.8238,  0.2310,  0.7357,  ..., -0.0598,  0.6222, -1.1008],
        [-0.3882,  1.0798, -0.3614,  ...,  0.8973,  0.8002,  1.0633]])

In [77]:
class Model(nn.Module):
    def __init__(self,newfeature):
        super().__init__()
        self.linear=nn.Linear(newfeature,16)
        self.relu=nn.ReLU()
        self.linear1=nn.Linear(16,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,feature):
        out=self.linear(feature)
        out=self.relu(out)
        out=self.linear1(out)
        out=self.sigmoid(out)
        return out



In [70]:
t=xtrain.shape[1]

t

30

In [91]:
learning_rate=0.1
epochs=30

loss=nn.BCELoss()
model=Model(t)

In [92]:

optimizer=torch.optim.SGD(model.parameters(),learning_rate)

In [93]:
for i in range(epochs):
    ypred = model(xtrain)
    loss_value = loss(ypred, ytrain.view(-1, 1))
    optimizer.zero_grad()
    loss_value.backward()
    optimizer.step()
    print(f'Loss at epoch {i}: {loss_value.item():.4f}')

Loss at epoch 0: 0.6780
Loss at epoch 1: 0.6502
Loss at epoch 2: 0.6243
Loss at epoch 3: 0.6000
Loss at epoch 4: 0.5770
Loss at epoch 5: 0.5551
Loss at epoch 6: 0.5341
Loss at epoch 7: 0.5140
Loss at epoch 8: 0.4947
Loss at epoch 9: 0.4761
Loss at epoch 10: 0.4583
Loss at epoch 11: 0.4413
Loss at epoch 12: 0.4251
Loss at epoch 13: 0.4097
Loss at epoch 14: 0.3950
Loss at epoch 15: 0.3810
Loss at epoch 16: 0.3678
Loss at epoch 17: 0.3553
Loss at epoch 18: 0.3434
Loss at epoch 19: 0.3322
Loss at epoch 20: 0.3216
Loss at epoch 21: 0.3116
Loss at epoch 22: 0.3022
Loss at epoch 23: 0.2933
Loss at epoch 24: 0.2849
Loss at epoch 25: 0.2769
Loss at epoch 26: 0.2694
Loss at epoch 27: 0.2622
Loss at epoch 28: 0.2554
Loss at epoch 29: 0.2490


In [102]:
from sklearn.datasets import make_classification

In [121]:
x,y= make_classification(
    n_samples=100,
    n_features=30,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42,
)


In [122]:
xtrain =torch.tensor(xtrain,dtype=torch.float32)
y=torch.tensor(y,dtype=torch.long)
from torch.utils.data import Dataset,DataLoader


C:\Users\AMAN KUMAR SINGH\AppData\Local\Temp\ipykernel_29084\2321399160.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  xtrain =torch.tensor(xtrain,dtype=torch.float32)


In [123]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels
    def __len__(self):
        return self.features.shape[0]
    def __getitem__(self,index):
        return self.features[index],self.labels[index]
    

In [124]:
dataset=CustomDataset(x,y)

In [125]:
len(dataset)

100

In [126]:
dataset[2]

(array([ 0.06428002,  0.08187414, -0.71530371,  0.85243333, -0.31526924,
        -0.6795874 ,  2.31465857, -0.48536355, -1.86726519, -1.61271587,
        -0.11473644, -0.73036663,  0.18645431,  1.0889506 ,  0.68626019,
         0.04557184,  0.63391902, -0.47193187, -0.66178646, -0.77282521,
         0.67959775, -1.07774478, -0.65160035, -0.81680628,  0.75896922,
        -0.23681861, -2.02514259, -0.79252074,  0.21645859,  2.14394409]),
 tensor(0))

In [129]:
dataloader=DataLoader(dataset,batch_size=4,shuffle=True)

In [130]:
for batch_feature,batch_labels in dataloader:
    print(batch_feature)
    print(batch_labels)
    print("-"*50)


tensor([[ 0.5388, -1.2096,  0.1694,  0.1417,  0.3309,  0.2447,  1.6726,  1.2277,
          0.4190, -0.0558,  0.3933, -0.1112, -0.3164,  0.0760, -0.7050, -0.7355,
          0.6091,  0.5583,  1.2131, -1.9937, -1.4137, -0.9207,  1.2361,  2.5912,
          0.8335,  0.3741, -1.0923,  2.3193, -0.9039,  1.0913],
        [ 2.6443, -0.2860,  0.2537, -0.0293, -1.0727,  1.9981,  1.1010, -2.5303,
          1.9583,  0.4967, -0.0514,  1.0858, -0.3696, -0.1059, -1.2295,  0.3081,
         -0.3432, -0.4653,  0.3771,  2.0741,  0.4677, -1.5030, -0.3916,  0.1551,
          0.2392, -0.9194,  0.6216,  1.1261,  0.0980,  0.2691],
        [-0.0827,  0.9553,  1.5134,  1.5432, -0.8182, -1.0054,  0.0884,  0.6964,
          1.4775, -0.1937, -1.1196, -1.0242,  1.0887, -1.8665, -1.1417,  1.2210,
         -0.9594, -0.7168,  1.8846, -0.1702,  0.6308, -0.1217,  0.5821,  1.0866,
         -0.0034, -0.4532, -0.3722, -0.4888,  1.8541, -0.2265],
        [-0.8037, -0.1470,  1.6777, -0.7700,  0.6338, -0.0219,  0.9639,  0.0438